#    SugarSubstitute - The desktop native Qt front-end for ComfyUI
#    Copyright (C) 2026  Artificial Sweetener and contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

from typing import Any

from PySide6.QtWidgets import QWidget

class WorkspaceSidePanelHost(QWidget):
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def set_queue_panel(self, panel: QWidget) -> None: ...
    def set_queue_panel_visible(self, visible: bool) -> None: ...
    def begin_width_transition(self, *, target_visible: bool) -> None: ...
    def apply_width_transition(self, width: int) -> None: ...
    def finish_width_transition(self, *, visible: bool) -> None: ...
    def is_queue_panel_visible(self) -> bool: ...
    def set_panel_width(self, width: int) -> None: ...
    def panel_width(self) -> int: ...
    def rendered_width(self) -> int: ...

def build_main_window_workspace(*args: Any, **kwargs: Any) -> Any: ...
