#    SugarSubstitute - The desktop native Qt front-end for ComfyUI
#    Copyright (C) 2026  Artificial Sweetener and contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

from typing import Any

class GenerationPreflightError(RuntimeError): ...

class WorkspaceController:
    def __init__(self, view: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    @property
    def file_actions(self) -> Any: ...
    @property
    def workflow_workspace(self) -> Any: ...
    @property
    def search_actions(self) -> Any: ...
    @property
    def cube_actions(self) -> Any: ...
    @property
    def canvas_actions(self) -> Any: ...
    @property
    def workflow_duplicate_service(self) -> Any: ...
    @property
    def generation_actions(self) -> Any: ...
    @property
    def scene_generation_actions(self) -> Any: ...
    @property
    def loaded_cube_surface_actions(self) -> Any: ...
    def build_generation_request(self) -> Any: ...
    def build_generation_snapshot(self) -> Any: ...
    def build_queued_generation_snapshots(self) -> tuple[Any, ...]: ...
    def build_scene_generation_snapshot(self, scene_key: str) -> Any: ...
    def build_scene_generation_snapshots(self) -> tuple[Any, ...]: ...
    def build_generation_bindings(self) -> Any: ...
    def on_input_canvas_image_loaded(self, *args: Any, **kwargs: Any) -> None: ...
