#    SugarSubstitute - The desktop native Qt front-end for ComfyUI
#    Copyright (C) 2026  Artificial Sweetener and contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

from typing import Any, Protocol

from substitute.application.workflows.output_visual_events import LivePreviewEvent

class MessageBoxProtocol(Protocol): ...
class WorkspaceCanvasActionView(Protocol): ...

class WorkspaceCanvasActions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def on_active_output_changed(self, *args: Any, **kwargs: Any) -> None: ...
    def on_active_output_grid_changed(self, *args: Any, **kwargs: Any) -> None: ...
    def on_output_compare_changed(self, *args: Any, **kwargs: Any) -> None: ...
    def display_preview_image(self, preview: LivePreviewEvent) -> None: ...
    def open_image_in_external_editor(self, *args: Any, **kwargs: Any) -> None: ...
    def open_images_in_external_editor(self, *args: Any, **kwargs: Any) -> None: ...
    def handle_add_output_image(self, *args: Any, **kwargs: Any) -> None: ...
    def commit_prepared_output_image(self, *args: Any, **kwargs: Any) -> Any: ...
    def handle_output_image_preparation_failed(
        self, *args: Any, **kwargs: Any
    ) -> None: ...
    def prepare_output_image_commit(self, *args: Any, **kwargs: Any) -> None: ...
    def update_canvas_callback(self, *args: Any, **kwargs: Any) -> None: ...
