#    SugarSubstitute - The desktop native Qt front-end for ComfyUI
#    Copyright (C) 2026  Artificial Sweetener and contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Describe the public Qt surface of a rendered cube-stack item."""

from typing import Any

class CubeItem:
    fixed_height: int
    selected_accent_position: str
    selected_bottom_corner_radius: float
    selected_bottom_corner_width: float
    selected_connects_to_bottom_surface: bool
    selected_fill_color: Any
    selected_bottom_border_mode: str
    unselected_separator_color: Any
    unselected_top_rounded_only: bool

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def beginCompactTransition(self, target_compact: bool) -> None: ...
    def finishCompactTransition(self, compact: bool) -> None: ...
    def compact_progress(self) -> float: ...
    def setCompactProgress(self, progress: float) -> None: ...
    def begin_alias_editing(self) -> bool: ...
    def setBypassed(self, bypassed: bool) -> None: ...
    def isBypassed(self) -> bool: ...
    def setCompact(self, compact: bool) -> None: ...
    def setSecondaryText(self, text: str) -> None: ...
    def setIssueSeverity(self, severity: object | None) -> None: ...
    def setFixedWidth(self, width: int) -> None: ...
    def routeKey(self) -> str | None: ...
