#    SugarSubstitute - The desktop native Qt front-end for ComfyUI
#    Copyright (C) 2026  Artificial Sweetener and contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

from typing import Any

from PySide6.QtCore import QSize
from PySide6.QtWidgets import QWidget

class CubeSectionWidgetParts:
    widget: CubeSectionView
    grid_layout: Any
    header_label: Any
    reveal_button: Any
    reveal_menu: Any

class CubeSectionView(QWidget):
    cube_height_changed: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def sizeHint(self) -> QSize: ...
    def minimumSizeHint(self) -> QSize: ...
    def reveal_anchor_y(self) -> int: ...
    def node_card_order(self) -> tuple[str, ...]: ...
    def finalize_layout_for_reveal(self, *, reason: str) -> None: ...
    def finalize_layout_after_child_relayout(self, *, reason: str) -> None: ...
    def update_cube_height(self) -> None: ...
    def defer_update_cube_height(self) -> None: ...
    def defer_string_line_edit_width_group_sync(self) -> None: ...
    def sync_string_line_edit_width_group(self) -> None: ...
    def showUpdatingWash(self, message: str = ...) -> None: ...
    def hideUpdatingWash(self) -> None: ...
    def setIssueSeverity(self, severity: str | None) -> None: ...
    def issueSeverity(self) -> str | None: ...
    def setIssueMessages(self, messages: tuple[str, ...]) -> None: ...
    def issueMessages(self) -> tuple[str, ...]: ...

class CubeSectionBuilder:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def build_cube_section(self, route_key: str) -> CubeSectionWidgetParts: ...
    def build_error_cube_widget(
        self,
        route_key: str,
        *,
        issue_lines: tuple[str, ...],
    ) -> CubeSectionView: ...
