#    SugarSubstitute - The desktop native Qt front-end for ComfyUI
#    Copyright (C) 2026  Artificial Sweetener and contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Type stubs for toggle-aware QFluent popup button wrappers."""

from __future__ import annotations

from typing import Protocol

class SignalLike(Protocol):
    """Describe the minimal signal surface used by the wrapper call sites."""

    def connect(self, callback: object) -> None: ...

class ButtonPartLike(Protocol):
    """Describe the split-button child widgets used by local call sites."""

    clicked: SignalLike

    def setFixedWidth(self, width: int) -> None: ...
    def setFixedHeight(self, height: int) -> None: ...
    def setMinimumWidth(self, width: int) -> None: ...
    def setMaximumWidth(self, width: int) -> None: ...
    def setStyleSheet(self, style: str) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...

class ToggleDropDownToolButton:
    """Close the attached menu on repeated clicks instead of reopening it."""

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def setMenu(self, menu: object) -> None: ...
    def setToolTip(self, tooltip: str) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setVisible(self, visible: bool) -> None: ...
    def setCursor(self, cursor: object) -> None: ...
    def mouseReleaseEvent(self, event: object) -> None: ...

class ToggleTransparentDropDownToolButton(ToggleDropDownToolButton):
    """Close the attached menu on repeated clicks for transparent tool buttons."""

class ToggleSplitToolButton:
    """Close the attached flyout on repeated drop-arrow clicks."""

    button: ButtonPartLike
    dropButton: ButtonPartLike
    clicked: SignalLike
    dropDownClicked: SignalLike

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def setFlyout(self, flyout: object) -> None: ...
    def setToolTip(self, tooltip: str) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setIcon(self, icon: object) -> None: ...
    def setCursor(self, cursor: object) -> None: ...
    def setFixedWidth(self, width: int) -> None: ...
    def setFixedHeight(self, height: int) -> None: ...
    def setMinimumWidth(self, width: int) -> None: ...
    def setMaximumWidth(self, width: int) -> None: ...

class TogglePrimarySplitPushButton(ToggleSplitToolButton):
    """Close the attached flyout on repeated drop-arrow clicks for primary buttons."""
